"use client";

import { useQuery } from "convex/react";
import {
  Activity,
  AlertTriangle,
  ArrowRight,
  Banknote,
  BookOpen,
  Bot,
  Building2,
  Clock3,
  Compass,
  Globe,
  History,
  MessageSquare,
  ShieldAlert,
  ShieldCheck,
  Smile,
  Sparkles,
  TrendingUp,
  User,
  Users,
} from "lucide-react";
import Link from "next/link";
import { api } from "@/convex/_generated/api";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { motion } from "motion/react";
import { Skeleton } from "@/components/ui/skeleton";

export default function AdminOverviewPage() {
  const stats = useQuery(api.admin.getOverviewStats);
  const recentConvos = useQuery(api.admin.listRecentConversations, { limit: 5 });

  const isLoading = stats === undefined || recentConvos === undefined;

  const formatKes = new Intl.NumberFormat("en-KE", {
    style: "currency",
    currency: "KES",
    maximumFractionDigits: 0,
  });

  const containerVariants = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: {
        staggerChildren: 0.04,
      },
    },
  } as const;

  const itemVariants = {
    hidden: { y: 15, opacity: 0 },
    show: { y: 0, opacity: 1, transition: { type: "spring", stiffness: 120, damping: 15 } },
  } as const;

  if (isLoading) {
    return (
      <div className="flex-1 space-y-6 p-6 md:p-8">
        <div className="flex items-center justify-between">
          <div className="space-y-1">
            <Skeleton className="h-8 w-48" />
            <Skeleton className="h-4 w-72" />
          </div>
        </div>

        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {Array.from({ length: 8 }).map((_, i) => (
            <Card key={i} className="overflow-hidden">
              <CardHeader className="flex flex-row items-center justify-between pb-2">
                <Skeleton className="h-4 w-24" />
                <Skeleton className="size-4 rounded-full" />
              </CardHeader>
              <CardContent>
                <Skeleton className="h-8 w-16 mb-2" />
                <Skeleton className="h-3 w-32" />
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    );
  }

  const aiResolutionRate = 100 - stats.aiPerformance.handoffRate;

  const totalAiReplies = stats.aiPerformance.groundedMessages + stats.aiPerformance.ungroundedMessages;
  const groundedPercentage = totalAiReplies > 0
    ? Math.round((stats.aiPerformance.groundedMessages / totalAiReplies) * 100)
    : 100;
  const ungroundedPercentage = 100 - groundedPercentage;

  const kpiCards = [
    {
      title: "Total Workspaces",
      value: stats.totalWorkspaces.toLocaleString(),
      subtitle: "Active business tenants",
      icon: Building2,
      tone: "from-red-500/20 to-red-500/5 text-red-600",
    },
    {
      title: "Platform Members",
      value: stats.totalMembers.toLocaleString(),
      subtitle: "Registered system operators",
      icon: Users,
      tone: "from-amber-500/20 to-amber-500/5 text-amber-600",
    },
    {
      title: "Conversations",
      value: stats.totalConversations.toLocaleString(),
      subtitle: "Total threads since creation",
      icon: MessageSquare,
      tone: "from-orange-500/20 to-orange-500/5 text-orange-600",
    },
    {
      title: "Estimated MRR",
      value: formatKes.format(stats.estimatedMRR),
      subtitle: "Monthly recurring revenue in Kenya Shillings",
      icon: Banknote,
      tone: "from-emerald-500/20 to-emerald-500/5 text-emerald-600",
    },
    {
      title: "Helpdesk Articles",
      value: stats.totalArticles.toLocaleString(),
      subtitle: "Published articles for RAG",
      icon: BookOpen,
      tone: "from-blue-500/20 to-blue-500/5 text-blue-600",
    },
    {
      title: "Crawled Pages",
      value: stats.totalCrawlPages.toLocaleString(),
      subtitle: "Pages in knowledge index",
      icon: Globe,
      tone: "from-cyan-500/20 to-cyan-500/5 text-cyan-600",
    },
    {
      title: "Leads Captured",
      value: stats.totalLeads.toLocaleString(),
      subtitle: "Contacts generated by widget",
      icon: Sparkles,
      tone: "from-indigo-500/20 to-indigo-500/5 text-indigo-600",
    },
    {
      title: "Lead Conversion Rate",
      value: `${stats.conversionRate}%`,
      subtitle: "Conversation to lead conversion",
      icon: TrendingUp,
      tone: "from-violet-500/20 to-violet-500/5 text-violet-600",
    },
  ] as const;

  const aiHealthCards = [
    {
      title: "Average AI Latency",
      value: `${stats.aiPerformance.averageResponseTimeSec}s`,
      subtitle: "Average turn response speed",
      icon: Clock3,
      tone: "bg-violet-500/10 text-violet-600",
    },
    {
      title: "User Sentiment Index",
      value: `${stats.aiPerformance.sentimentScore}%`,
      subtitle: "Positive or neutral conversation ratio",
      icon: Smile,
      tone: "bg-emerald-500/10 text-emerald-600",
    },
    {
      title: "Guardrail Violations",
      value: stats.aiPerformance.guardrailTriggers.toLocaleString(),
      subtitle: "Blocked jailbreak or injection probes",
      icon: ShieldAlert,
      tone:
        stats.aiPerformance.guardrailTriggers > 0
          ? "bg-red-500/20 text-red-600"
          : "bg-muted text-muted-foreground",
    },
    {
      title: "AI Grounding Accuracy",
      value: `${groundedPercentage}%`,
      subtitle: "RAG-sourced replies",
      icon: ShieldCheck,
      tone: "bg-blue-500/10 text-blue-600",
    },
  ] as const;

  return (
    <div className="flex-1 space-y-6 overflow-y-auto bg-muted/10 p-6 md:p-8 h-screen">
      <motion.section
        initial={{ opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.35 }}
        className="relative overflow-hidden rounded-3xl border bg-gradient-to-br from-red-50 via-background to-amber-50 p-6 shadow-soft dark:from-red-950/20 dark:via-background dark:to-amber-950/20"
      >
        <div className="absolute -right-16 -top-20 size-56 rounded-full bg-red-500/10 blur-3xl" />
        <div className="absolute -bottom-24 left-16 size-64 rounded-full bg-amber-500/10 blur-3xl" />

        <div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between">
          <div className="space-y-3">
            <Badge className="bg-red-500/10 text-red-700 hover:bg-red-500/20 dark:text-red-300">
              Platform Admin
            </Badge>
            <div>
              <h1 className="text-3xl font-extrabold tracking-tight text-foreground md:text-4xl">
                System Overview
              </h1>
              <p className="mt-1 text-sm font-medium text-muted-foreground md:text-base">
                Live platform health, grounding quality, and support performance across tenants.
              </p>
            </div>
            <div className="grid grid-cols-2 gap-3 pt-1 sm:grid-cols-3">
              <div className="rounded-xl border bg-background/70 px-3 py-2 backdrop-blur-sm">
                <p className="text-[11px] uppercase tracking-wider text-muted-foreground">MRR (KSh)</p>
                <p className="text-lg font-bold text-foreground">{formatKes.format(stats.estimatedMRR)}</p>
              </div>
              <div className="rounded-xl border bg-background/70 px-3 py-2 backdrop-blur-sm">
                <p className="text-[11px] uppercase tracking-wider text-muted-foreground">Grounded Replies</p>
                <p className="text-lg font-bold text-foreground">{groundedPercentage}%</p>
              </div>
              <div className="rounded-xl border bg-background/70 px-3 py-2 backdrop-blur-sm col-span-2 sm:col-span-1">
                <p className="text-[11px] uppercase tracking-wider text-muted-foreground">Avg Latency</p>
                <p className="text-lg font-bold text-foreground">{stats.aiPerformance.averageResponseTimeSec}s</p>
              </div>
            </div>
          </div>

          <Link href="/admin/ai-behavior">
            <Button className="h-11 rounded-xl bg-gradient-to-r from-red-600 to-amber-500 px-4 text-white shadow-soft transition-all hover:from-red-700 hover:to-amber-600 hover:shadow-soft-lg">
              <Bot className="mr-1.5 size-4" />
              Open AI Behavior Dashboard
              <ArrowRight className="ml-1.5 size-4" />
            </Button>
          </Link>
        </div>
      </motion.section>

      <motion.div
        variants={containerVariants}
        initial="hidden"
        animate="show"
        className="space-y-6"
      >
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
          {kpiCards.map((card) => {
            const Icon = card.icon;
            return (
              <motion.div
                key={card.title}
                variants={itemVariants}
                whileHover={{ scale: 1.015, y: -2 }}
                className="transition-all duration-300"
              >
                <Card className="overflow-hidden border-border bg-card/70 shadow-soft backdrop-blur-md transition-all hover:shadow-soft-lg">
                  <CardHeader className="pb-2">
                    <div className="flex items-center justify-between">
                      <span className="text-xs font-bold uppercase tracking-wider text-muted-foreground">
                        {card.title}
                      </span>
                      <span className={`flex size-8 items-center justify-center rounded-lg bg-gradient-to-br ${card.tone}`}>
                        <Icon className="size-4" />
                      </span>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <p className="text-2xl font-bold tracking-tight text-foreground">{card.value}</p>
                    <p className="mt-1 text-xs font-medium text-muted-foreground">{card.subtitle}</p>
                  </CardContent>
                </Card>
              </motion.div>
            );
          })}
        </div>

        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
          {aiHealthCards.map((card) => {
            const Icon = card.icon;
            return (
              <motion.div
                key={card.title}
                variants={itemVariants}
                whileHover={{ scale: 1.015, y: -2 }}
                className="transition-all duration-300"
              >
                <Card className="overflow-hidden border-border bg-card/70 shadow-soft backdrop-blur-md transition-all hover:shadow-soft-lg">
                  <CardHeader className="flex flex-row items-center justify-between pb-2">
                    <span className="text-xs font-bold uppercase tracking-wider text-muted-foreground">
                      {card.title}
                    </span>
                    <span className={`flex size-8 items-center justify-center rounded-lg ${card.tone}`}>
                      <Icon className="size-4" />
                    </span>
                  </CardHeader>
                  <CardContent>
                    <p className="text-2xl font-bold tracking-tight text-foreground">{card.value}</p>
                    <p className="mt-1 text-xs font-medium text-muted-foreground">{card.subtitle}</p>
                  </CardContent>
                </Card>
              </motion.div>
            );
          })}
        </div>

        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-7">
          <motion.div variants={itemVariants} className="lg:col-span-4 space-y-6">
            <Card className="border-border bg-card/40 backdrop-blur-md shadow-soft">
              <CardHeader>
                <div className="flex items-center gap-2">
                  <span className="flex size-6 items-center justify-center rounded bg-red-500/10 text-red-500 animate-pulse">
                    <Bot className="size-4" />
                  </span>
                  <CardTitle className="text-lg">AI Behavior & RAG Insights</CardTitle>
                </div>
                <CardDescription>
                  Evaluating grounding metrics, RAG similarity scores, and hallucination risks.
                </CardDescription>
              </CardHeader>

              <CardContent className="space-y-6">
                <div className="grid gap-6 sm:grid-cols-2 border-b border-border/60 pb-6">
                  <div className="flex flex-col items-center justify-center border-r border-border/40 pr-2">
                    <div className="relative flex size-24 items-center justify-center rounded-full border-4 border-muted">
                      <svg className="absolute size-full -rotate-90">
                        <circle
                          cx="48"
                          cy="48"
                          r="44"
                          className="stroke-red-500 fill-none"
                          strokeWidth="8"
                          strokeDasharray={276}
                          strokeDashoffset={276 - (276 * aiResolutionRate) / 100}
                          strokeLinecap="round"
                        />
                      </svg>
                      <div className="text-center">
                        <span className="text-xl font-extrabold text-foreground">{aiResolutionRate}%</span>
                      </div>
                    </div>
                    <span className="mt-3 text-xs font-bold text-muted-foreground uppercase tracking-wider text-center">
                      AI Resolution Rate
                    </span>
                  </div>

                  <div className="space-y-4">
                    <h4 className="text-xs font-bold uppercase tracking-wider text-muted-foreground">
                      Hallucination Risk Audit
                    </h4>

                    <div className="space-y-2">
                      <div className="flex justify-between items-center text-xs font-medium">
                        <span className="text-muted-foreground flex items-center gap-1.5">
                          <ShieldCheck className="size-3.5 text-emerald-500" />
                          Grounded Replies
                        </span>
                        <span className="text-foreground font-bold">{groundedPercentage}%</span>
                      </div>
                      <div className="relative h-2 w-full rounded-full bg-muted overflow-hidden">
                        <div
                          className="h-full bg-emerald-500 rounded-full transition-all"
                          style={{ width: `${groundedPercentage}%` }}
                        />
                      </div>
                    </div>

                    <div className="space-y-2">
                      <div className="flex justify-between items-center text-xs font-medium">
                        <span className="text-muted-foreground flex items-center gap-1.5">
                          <AlertTriangle className="size-3.5 text-rose-500 animate-pulse" />
                          Ungrounded (Hallucination Risk)
                        </span>
                        <span className="text-foreground font-bold">{ungroundedPercentage}%</span>
                      </div>
                      <div className="relative h-2 w-full rounded-full bg-muted overflow-hidden">
                        <div
                          className="h-full bg-rose-500 rounded-full transition-all"
                          style={{ width: `${ungroundedPercentage}%` }}
                        />
                      </div>
                    </div>

                    <p className="text-[10px] leading-relaxed text-muted-foreground font-medium border-t border-border/40 pt-2">
                      Grounded replies rely directly on indexed knowledge articles/crawler text. Ungrounded replies are generated when vector retrieval falls below the score threshold.
                    </p>
                  </div>
                </div>

                <div className="space-y-3">
                  <h4 className="text-xs font-bold uppercase tracking-wider text-muted-foreground flex items-center gap-1.5">
                    <Compass className="size-3.5 text-red-500" />
                    Top Cited RAG Sources
                  </h4>

                  {stats.aiPerformance.topCitedSources.length === 0 ? (
                    <div className="text-xs text-muted-foreground py-2 italic">
                      No grounding citations recorded yet.
                    </div>
                  ) : (
                    <div className="space-y-2 bg-muted/30 border rounded-lg p-3">
                      {stats.aiPerformance.topCitedSources.map((source, i) => (
                        <div key={i} className="flex justify-between items-center text-xs last:border-b-0 pb-1.5 border-b border-border/40 last:pb-0">
                          <span className="text-foreground font-semibold truncate max-w-[280px]">
                            {source.title}
                          </span>
                          <Badge variant="secondary" className="text-[10px] px-1.5 py-0">
                            {source.count} citations
                          </Badge>
                        </div>
                      ))}
                    </div>
                  )}
                </div>

                <div className="space-y-4 border-t border-border/60 pt-4">
                  <div className="flex items-center justify-between">
                    <h4 className="text-sm font-semibold tracking-tight text-foreground flex items-center gap-1.5">
                      <Activity className="size-3.5 text-red-500" />
                      Message Distribution
                    </h4>
                    <span className="text-xs text-muted-foreground font-bold">
                      Total: {stats.totalMessages}
                    </span>
                  </div>

                  <div className="space-y-3.5">
                    <div className="space-y-1">
                      <div className="flex justify-between text-xs font-medium">
                        <span className="text-muted-foreground flex items-center gap-1.5">
                          <User className="size-3 text-muted-foreground" />
                          Visitor Messages
                        </span>
                        <span className="text-foreground font-semibold">
                          {stats.messageBreakdown.visitor} ({stats.totalMessages > 0 ? Math.round((stats.messageBreakdown.visitor / stats.totalMessages) * 100) : 0}%)
                        </span>
                      </div>
                      <div className="relative h-1.5 w-full rounded-full bg-muted overflow-hidden">
                        <div
                          className="h-full bg-brand rounded-full transition-all"
                          style={{ width: `${stats.totalMessages > 0 ? (stats.messageBreakdown.visitor / stats.totalMessages) * 100 : 0}%` }}
                        />
                      </div>
                    </div>

                    <div className="space-y-1">
                      <div className="flex justify-between text-xs font-medium">
                        <span className="text-muted-foreground flex items-center gap-1.5">
                          <Bot className="size-3 text-red-500" />
                          AI Agent Responses
                        </span>
                        <span className="text-foreground font-semibold">
                          {stats.messageBreakdown.aiAgent} ({stats.totalMessages > 0 ? Math.round((stats.messageBreakdown.aiAgent / stats.totalMessages) * 100) : 0}%)
                        </span>
                      </div>
                      <div className="relative h-1.5 w-full rounded-full bg-red-100 dark:bg-red-950/20 overflow-hidden">
                        <div
                          className="h-full bg-red-500 rounded-full transition-all"
                          style={{ width: `${stats.totalMessages > 0 ? (stats.messageBreakdown.aiAgent / stats.totalMessages) * 100 : 0}%` }}
                        />
                      </div>
                    </div>

                    <div className="space-y-1">
                      <div className="flex justify-between text-xs font-medium">
                        <span className="text-muted-foreground flex items-center gap-1.5">
                          <Users className="size-3 text-amber-500" />
                          Human Agent Replies
                        </span>
                        <span className="text-foreground font-semibold">
                          {stats.messageBreakdown.humanAgent} ({stats.totalMessages > 0 ? Math.round((stats.messageBreakdown.humanAgent / stats.totalMessages) * 100) : 0}%)
                        </span>
                      </div>
                      <div className="relative h-1.5 w-full rounded-full bg-amber-100 dark:bg-amber-950/20 overflow-hidden">
                        <div
                          className="h-full bg-amber-500 rounded-full transition-all"
                          style={{ width: `${stats.totalMessages > 0 ? (stats.messageBreakdown.humanAgent / stats.totalMessages) * 100 : 0}%` }}
                        />
                      </div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </motion.div>

          <motion.div variants={itemVariants} className="lg:col-span-3">
            <Card className="h-full border-border bg-card/40 backdrop-blur-md shadow-soft flex flex-col">
              <CardHeader className="pb-3">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="flex size-6 items-center justify-center rounded bg-amber-500/10 text-amber-500">
                      <History className="size-4" />
                    </span>
                    <CardTitle className="text-lg">Recent Chats</CardTitle>
                  </div>
                  <Link href="/admin/workspaces">
                    <Button variant="ghost" size="sm" className="h-7 text-xs font-semibold px-2">
                      View all
                    </Button>
                  </Link>
                </div>
                <CardDescription>
                  Latest interactions across workspaces.
                </CardDescription>
              </CardHeader>
              <CardContent className="flex-1 p-0 px-4 pb-4">
                <div className="divide-y divide-border/60">
                  {recentConvos.length === 0 ? (
                    <div className="text-center py-8 text-sm text-muted-foreground">
                      No recent active conversations found.
                    </div>
                  ) : (
                    recentConvos.map((convo) => (
                      <div key={convo._id} className="py-3 first:pt-0 last:pb-0 flex items-start justify-between gap-3 text-sm">
                        <div className="space-y-1 min-w-0 flex-1">
                          <div className="flex items-center gap-2">
                            <span className="font-semibold text-foreground truncate">
                              {convo.visitorName}
                            </span>
                            <span className="text-[10px] text-muted-foreground font-semibold uppercase tracking-wider truncate max-w-[100px]">
                              @{convo.workspaceName}
                            </span>
                          </div>
                          <p className="text-xs text-muted-foreground line-clamp-1 break-all">
                            {convo.preview}
                          </p>
                        </div>
                        <div className="flex flex-col items-end gap-1.5 shrink-0">
                          <Badge
                            variant="outline"
                            className={`text-[10px] px-1.5 py-0 font-semibold ${
                              convo.mode === "human"
                                ? "bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/20"
                                : "bg-red-500/10 text-red-600 dark:text-red-400 border-red-500/20"
                            }`}
                          >
                            {convo.mode === "human" ? "Human" : "AI"}
                          </Badge>
                          <span className="text-[10px] text-muted-foreground font-semibold">
                            {new Date(convo.lastMessageAt).toLocaleTimeString([], {
                              hour: "2-digit",
                              minute: "2-digit",
                            })}
                          </span>
                        </div>
                      </div>
                    ))
                  )}
                </div>
              </CardContent>
            </Card>
          </motion.div>
        </div>
      </motion.div>
    </div>
  );
}
